### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'unpacked/system1.img'

### ISSUE THREAD

**Issue by imKota** [dipcore/mstar-bin-tool#1]
Error unpacking:C
firmware link [link](https://cloud.mail.ru/public/Dft4/cuQbvRgnZ)

```
➜  python2 unpack.py /Users/kota/Downloads/V8-S68AT02-LF1V150.bin                                                                                                                               ruby-2.4.0 
[i] Analizing header ...
Traceback (most recent call last):
  File "unpack.py", line 41, in <module>
    offset = header.find('\xff'.encode(encoding='iso-8859-1'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xff in position 0: ordinal not in range(128)
kota@iMac—Kota ~/Downloads/mstar-bin-tool-master
```

```
➜  python3 unpack.py /Users/kota/Downloads/V8-S68AT02-LF1V150.bin                                                                                                                               ruby-2.4.0 
[i] Analizing header ...
[i] Saving header script to unpacked/~header_script ...
[i] Parsing script ...
[i] Partition: sboot	Offset: 0x4000	Size 0x13800 (78.0 KB) -> unpacked/sboot.img
[i] Partition: MBOOT	Offset: 0x18000	Size 0x183200 (1.51 MB) -> unpacked/MBOOT.img
[i] Partition: recovery	Offset: 0x19c000	Size 0x1643b40 (22.26 MB) -> unpacked/recovery.img
[i] Partition: boot	Offset: 0x17e1000	Size 0xd79f90 (13.48 MB) -> unpacked/boot.img
[i] Partition: tee	Offset: 0x255c000	Size 0x3012d0 (3.0 MB) -> unpacked/tee.img
[i] Partition: RTPM	Offset: 0x2860000	Size 0x10000 (64.0 KB) -> unpacked/RTPM.img
[i] Partition: dtb	Offset: 0x2870000	Size 0xa34 (2.55 KB) -> unpacked/dtb.img
[i] Partition: frc	Offset: 0x2871000	Size 0x71010 (452.02 KB) -> unpacked/frc.img
[i] Partition: tclconfig	Offset: 0x28e3000	Size 0x627083 (6.15 MB) -> unpacked/tclconfig.lzo
[i]     Unpacking LZO (Please be patient) unpacked/tclconfig.lzo -> unpacked/tclconfig.img
sh: bin/linux-x86/lzop: No such file or directory
[i] Partition: database	Offset: 0x2f0b000	Size 0x12e6b (75.6 KB) -> unpacked/database.lzo
[i]     Unpacking LZO (Please be patient) unpacked/database.lzo -> unpacked/database.img
sh: bin/linux-x86/lzop: No such file or directory
[i] Partition: tvos	Offset: 0x2f1e000	Size 0x48a7906 (72.65 MB) -> unpacked/tvos.lzo
[i]     Unpacking LZO (Please be patient) unpacked/tvos.lzo -> unpacked/tvos.img
sh: bin/linux-x86/lzop: No such file or directory
[i] Partition: system	Offset: 0x77c6000	Size 0x5e548fb (94.33 MB) -> unpacked/system.lzo
[i]     Unpacking LZO (Please be patient) unpacked/system.lzo -> unpacked/system.img
sh: bin/linux-x86/lzop: No such file or directory
[i] Partition: system	Offset: 0xd61b000	Size 0x6b74615 (107.45 MB) -> unpacked/system1.lzo
[i]     Unpacking LZO (Please be patient) unpacked/system1.lzo -> unpacked/system1.img
sh: bin/linux-x86/lzop: No such file or directory
[i]     unpacked/system1.img append to unpacked/system.img
Traceback (most recent call last):
  File "unpack.py", line 132, in <module>
    utils.appendFile(outputChunkImgFile, outputImgFile)
  File "/Users/kota/Downloads/mstar-bin-tool-master/utils.py", line 80, in appendFile
    with open(src, 'rb') as f1:
FileNotFoundError: [Errno 2] No such file or directory: 'unpacked/system1.img'
kota@iMac—Kota ~/Downloads/mstar-bin-tool-master
```
```
127|shell@blueberry:/ # mount                                                  
rootfs / rootfs ro,relatime 0 0
tmpfs /dev tmpfs rw,nosuid,relatime,mode=755 0 0
devpts /dev/pts devpts rw,relatime,mode=600 0 0
proc /proc proc rw,relatime 0 0
sysfs /sys sysfs rw,relatime 0 0
debugfs /sys/kernel/debug debugfs rw,relatime 0 0
none /acct cgroup rw,relatime,cpuacct 0 0
none /sys/fs/cgroup tmpfs rw,relatime,mode=750,gid=1000 0 0
tmpfs /mnt/asec tmpfs rw,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/obb tmpfs rw,relatime,mode=755,gid=1000 0 0
none /dev/cpuctl cgroup rw,relatime,cpu 0 0
tmpfs /mnt/usb tmpfs rw,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/iso tmpfs rw,relatime,mode=755,gid=1000 0 0
tmpfs /mnt/samba tmpfs rw,relatime,mode=755,gid=1000 0 0
tmpfs /var tmpfs rw,relatime,mode=775,gid=1000 0 0
/dev/block/platform/mstar_mci.0/by-name/system /system ext4 rw,relatime,data=ordered 0 0
/dev/block/platform/mstar_mci.0/by-name/cache /cache ext4 rw,nosuid,nodev,noatime,nodiratime,nodelalloc,journal_checksum,noauto_da_alloc,data=ordered 0 0
/dev/block/platform/mstar_mci.0/by-name/userdata /data ext4 rw,nosuid,nodev,noatime,nodiratime,nodelalloc,journal_checksum,noauto_da_alloc,data=ordered 0 0
/dev/block/platform/mstar_mci.0/by-name/tvos /tvos ext4 ro,relatime,data=ordered 0 0
/dev/block/platform/mstar_mci.0/by-name/tclconfig /tclconfig ext4 ro,relatime,data=ordered 0 0
/dev/block/platform/mstar_mci.0/by-name/database /userdata ext4 rw,nosuid,nodev,noatime,nodiratime,nodelalloc,journal_checksum,noauto_da_alloc,data=ordered 0 0
/dev/block/platform/mstar_mci.0/by-name/impdat /impdat ext4 ro,relatime,data=ordered 0 0
/dev/fuse /storage/sdcard0 fuse rw,nosuid,nodev,noexec,relatime,user_id=1023,group_id=1023,default_permissions,allow_other 0 0
tmpfs /userdata/epg tmpfs rw,relatime,size=32768k,mode=777 0 0
/dev/block/vold/8:1 /mnt/usb/4476-9A02 vfat rw,dirsync,nosuid,nodev,noexec,relatime,uid=1023,gid=1023,fmask=0000,dmask=0000,allow_utime=0022,codepage=437,iocharset=iso8859-1,shortname=mixed,utf8,errors=remount-ro 0 0

```

**Comment by imKota** [comment]
copy lzop to bin/linux-x86/lzop

**Comment by 1geta** [comment]
on Windows.
copy bin to work directory.~
