### ISSUE TITLE
problem to unpack

### ISSUE THREAD

**Issue by uNbAs** [dipcore/mstar-bin-tool#16]
unbas@W4rM4ChiN3:~/Descargas/mstar-bin-tool-master$ python3.7 unpack.py ../XGIMI_H2_CN_v.1.12.36_FW-MOD_01/GIMI_XHAD01_XHC05_MAXIM_YN_WMP.bin 
[i] Analizing header ...
[i] Saving header script to unpacked/~header_script ...
[i] Parsing script ...
[i] Partition: sboot	Offset: 0x4000	Size 0x13800 (78.0 KB) -> unpacked/sboot.img
[i] Partition: MBOOT	Offset: 0x18000	Size 0x294c00 (2.58 MB) -> unpacked/MBOOT.img
[i] Partition: recovery	Offset: 0x2ad000	Size 0x19df858 (25.87 MB) -> unpacked/recovery.img
[i] Parsing setenv recoverycmd -> mmc read.p 0x23000000 dtb 0x00100000\; mmc read.p 0x25000000 recovery 0x01E00000\; bootm 0x25000000
[i] Partition: boot	Offset: 0x1c8d000	Size 0x12883f0 (18.53 MB) -> unpacked/boot.img
[i] Parsing setenv bootcmd -> mmc read.p 0x23000000 dtb 0x00100000\; mmc read.p 0x25000000 boot 0x01400000\; bootm 0x25000000
[i] Partition: optee	Offset: 0x2f16000	Size 0x17b7f0 (1.48 MB) -> unpacked/optee.img
[i] Partition: armfw	Offset: 0x3092000	Size 0xa270 (40.61 KB) -> unpacked/armfw.img
[i] Partition: RTPM	Offset: 0x309d000	Size 0x10000 (64.0 KB) -> unpacked/RTPM.img
[i] Partition: dtb	Offset: 0x30ad000	Size 0x11e7 (4.48 KB) -> unpacked/dtb.img
[i] Partition: frc	Offset: 0x30af000	Size 0x8d010 (564.02 KB) -> unpacked/frc.img
[i] Partition: system	Offset: 0x313d000	Size 0x50eedcc (80.93 MB) -> unpacked/system.lzo
[i]     Unpacking LZO (Please be patient) unpacked/system.lzo -> unpacked/system.img
sh: 1: bin/linux-x86/lzop: not found
[i] Partition: system	Offset: 0x822c000	Size 0x75ec3bf (117.92 MB) -> unpacked/system1.lzo
[i]     Unpacking LZO (Please be patient) unpacked/system1.lzo -> unpacked/system1.img
sh: 1: bin/linux-x86/lzop: not found
[i]     unpacked/system1.img append to unpacked/system.img
Traceback (most recent call last):
  File "unpack.py", line 147, in <module>
    utils.appendFile(outputChunkImgFile, outputImgFile)
  File "/home/unbas/Descargas/mstar-bin-tool-master/utils.py", line 83, in appendFile
    with open(src, 'rb') as f1:
FileNotFoundError: [Errno 2] No such file or directory: 'unpacked/system1.img'

**Comment by 283330601** [comment]
LZOP component is missing, you can try to unpack in windows.

**Comment by uNbAs** [comment]
Thanks!
